#!/bin/bash
#SBATCH --job-name=analysis
#SBATCH --output=analysis.out
#SBATCH --error=analysis.err
#SBATCH --ntasks=48
#SBATCH --qos=debug
#SBATCH --time=00-01:00:00

module load ANACONDA/2019.10
module load intel mkl impi gcc # 2> /dev/null
module load impi
module load boost/1.64.0

eval "$(conda shell.bash hook)"
conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.0

python script.py
