#!/bin/bash
#SBATCH -J PELEne
#SBATCH --output=PELEne.out
#SBATCH --error=PELEne.err
#SBATCH --ntasks=48
#SBATCH --qos=debug
#SBATCH --time=00:10:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0

mpirun -np 48 /gpfs/projects/bsc72/PELE++/mniv/V1.7.2-b5/bin/PELE-1.7_mpi --control-file /mnt/c/Users/Ignasi/Desktop/Ignasi/Estudis/PhD/code/code_pelissimo/strain/LIG_linen_cry/pele.conf --license-directory /gpfs/projects/bsc72/PELE++/license
