#!/bin/bash
#SBATCH -J PELEne
#SBATCH --output=PELEne.out
#SBATCH --error=PELEne.err
#SBATCH --qos=debug
#SBATCH --time=00:30:00

module purge
module load intel mkl impi gcc
module load impi
module load python/2.7.13 boost/1.64.0_py2

mpirun -np 48 /gpfs/projects/bsc72/PELE++/mniv/V1.7.2-b2/bin/PELE-1.7.2_mpi --control-file /mnt/c/Users/Ignasi/Desktop/Ignasi/Estudis/PhD/code/code_pelissimo/strain/crystal/LIG_linen_cry/pele.conf --license-directory /gpfs/projects/bsc72/PELE++/license
