#!/bin/bash
#SBATCH -J n_1K27
#SBATCH --output=PELE.out
#SBATCH --error=PELE.err
#SBATCH --ntasks=48
#SBATCH --qos=debug
#SBATCH --time=00-00:30:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0
module load ANACONDA/2019.10

eval "$(conda shell.bash hook)"

conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.2

python -m pele_platform.main input.yaml 
