#!/bin/bash
#SBATCH -J PELEnergy
#SBATCH --output=PELE.out
#SBATCH --error=PELE.err
#SBATCH --qos=debug
#SBATCH --time=01:00:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0

list="D A F B E G H C"

for i in $list
do

    echo "--------------------------------------------------------------------"
    echo "|                            CLUSTER $i                            |"
    echo "--------------------------------------------------------------------"
    /gpfs/projects/bsc72/PELE++/mniv/V1.7.1/bin/PELE-1.7.1_serial /gpfs/projects/bsc72/ignasi/PhD/strain/second_set/MTAP/OPLS/normal/1CB0/LIG_peleRes/simulation/cluster_${i}/energy${i}.conf
    echo " "
    echo "*******************************************************************"
    echo "*******************************************************************"
    echo " "

done
