#!/bin/bash
#SBATCH -J B
#SBATCH --output=PELE.out
#SBATCH --error=PELE.err
#SBATCH --ntasks=4
#SBATCH --qos=debug
#SBATCH --time=01:00:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0

/gpfs/projects/bsc72/PELE++/mniv/V1.7.1/bin/PELE-1.7.1_serial energyB.conf
