#!/bin/bash
#SBATCH -J job_name
#SBATCH --output=PELE.out
#SBATCH --error=PELE.err
#SBATCH --ntasks=1
#SBATCH --qos=debug
#SBATCH --time=00-01:00:00

module purge
module load intel mkl impi gcc
module load impi
module load boost/1.64.0
module load ANACONDA/2019.10

eval "$(conda shell.bash hook)"

conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.2

python /home/bsc72/bsc72825/projects/code/dihedral_clustering.py -f ligand.pdb
